apiVersion: apps/v1
kind: Deployment
metadata:
  name: opds-chatapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opds-chatapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opds-chatapi
    spec:
      containers:
        - name: opds-chatapi
          image: hongjoong/opds-chatapi:0.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 9000
          volumeMounts:
          - name: chatapi-setting
            mountPath: /app/config/
            readOnly: false
          - name: tz-seoul
            mountPath: /etc/localtime
      volumes:
      - name: chatapi-setting
        configMap:
           name: chatapi-setting-config
      - name: tz-seoul
        hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul

